# Generated by Django 3.1.4 on 2020-12-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0008_auto_20201221_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
