# Generated by Django 3.1.4 on 2020-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0013_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='para',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='posts',
            name='para',
            field=models.CharField(max_length=500),
        ),
    ]
