# Generated by Django 3.1.4 on 2020-12-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0014_auto_20201222_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='para',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='posts',
            name='para',
            field=models.CharField(max_length=10000),
        ),
    ]
