# Generated by Django 3.1.4 on 2020-12-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0019_auto_20201222_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='video',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
