# Generated by Django 3.1.4 on 2020-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0020_auto_20201223_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medias',
            name='video',
        ),
        migrations.AddField(
            model_name='medias',
            name='video_Link',
            field=models.URLField(null=True),
        ),
    ]
