# Generated by Django 3.1.4 on 2020-12-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0021_auto_20201223_0918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MEDIAS',
        ),
    ]
