# Generated by Django 3.1.4 on 2020-12-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0022_delete_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEDIAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Link', models.URLField(null=True)),
            ],
        ),
    ]
