# Generated by Django 3.1.4 on 2020-12-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0027_auto_20201223_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='video_Link',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
