# Generated by Django 3.1.4 on 2020-12-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0029_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadmin',
            name='age',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
