# Generated by Django 3.1.4 on 2020-12-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0030_auto_20201224_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupadmin',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
