# Generated by Django 3.1.4 on 2020-12-27 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0031_auto_20201224_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MEDIAS',
        ),
    ]
