# Generated by Django 3.1.4 on 2020-12-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0032_delete_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='MEDIAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_Link', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
