# Generated by Django 3.1.4 on 2020-12-27 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0034_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Videos',
        ),
    ]
