# Generated by Django 3.1.4 on 2020-12-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0035_auto_20201227_1359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MEDIAS',
        ),
    ]
