# Generated by Django 3.1.4 on 2020-12-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0036_delete_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='JOBINTERNSHIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_of_intrest', models.CharField(max_length=50)),
                ('desired_duration', models.DateField(null=True)),
                ('starting_month', models.DateField(null=True)),
                ('brief_detail', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Mobile_no', models.IntegerField(max_length=50)),
                ('adhar_no', models.IntegerField(max_length=50)),
                ('gender_male', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('about_you', models.CharField(max_length=500)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('image', models.FileField(null=True, upload_to='')),
                ('para', models.CharField(max_length=10000)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VOLUNTEERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.FileField(null=True, upload_to='')),
                ('para', models.CharField(max_length=10000)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
