# Generated by Django 3.1.4 on 2020-12-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0037_jobinternship_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinternship',
            name='Mobile_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobinternship',
            name='adhar_no',
            field=models.IntegerField(null=True),
        ),
    ]
