# Generated by Django 3.1.4 on 2020-12-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0038_auto_20201227_2101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VOLUNTEERS',
        ),
        migrations.RenameField(
            model_name='jobinternship',
            old_name='gender_male',
            new_name='gender',
        ),
    ]
