# Generated by Django 3.1.4 on 2020-12-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0039_auto_20201227_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='VOLUNTEERS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('Mobile_no', models.IntegerField(null=True)),
                ('adhar_no', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('education', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('block', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('any_organization', models.CharField(max_length=50)),
                ('nyp_camp', models.CharField(max_length=50)),
                ('about_you', models.CharField(max_length=500)),
                ('your_photo', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
