# Generated by Django 3.1.4 on 2020-12-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0041_auto_20201227_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinternship',
            name='resume',
        ),
    ]
