# Generated by Django 3.1.4 on 2020-12-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0042_remove_jobinternship_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinternship',
            name='Resume',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
