# Generated by Django 3.1.4 on 2020-12-28 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0047_remove_volunteers_your_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
