# Generated by Django 3.1.4 on 2020-12-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0048_group_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinternship',
            name='approve',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='approve',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
