# Generated by Django 3.1.4 on 2020-12-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0049_auto_20201228_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinternship',
            name='approve',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='volunteers',
            name='approve',
            field=models.CharField(default=False, max_length=5),
        ),
    ]
