# Generated by Django 3.1.4 on 2020-12-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0051_volunteers_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteers',
            name='approve',
        ),
        migrations.AddField(
            model_name='volunteers',
            name='is_published',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12),
        ),
    ]
