# Generated by Django 3.1.4 on 2020-12-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0052_auto_20201228_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
