# Generated by Django 3.1.4 on 2020-12-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0054_auto_20201228_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobinternship',
            name='approve',
        ),
        migrations.AddField(
            model_name='jobinternship',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobinternship',
            name='is_published',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12),
        ),
    ]
