# Generated by Django 3.1.4 on 2020-12-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0055_auto_20201228_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='groupadmin',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
