# Generated by Django 3.1.4 on 2020-12-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0056_auto_20201228_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_published',
            field=models.CharField(choices=[('activated', 'Activated'), ('deactivated', 'Deactivated')], default='deactivated', max_length=12),
        ),
    ]
