# Generated by Django 3.1.4 on 2020-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0059_auto_20201229_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='activatedate',
            field=models.DateField(null=True),
        ),
    ]
