# Generated by Django 3.1.4 on 2020-12-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0060_auto_20201229_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='activatedate',
            field=models.DateField(null=True),
        ),
    ]
