# Generated by Django 3.1.4 on 2020-12-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youth', '0063_auto_20201229_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=900, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
